version: '3'
services:
  jupyterlab-ds:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/home/work"
      - ".jupyter:/root/.jupyter"
    ports:
      - "8080:8080"
    tty: true
    command: jupyter lab --ip=0.0.0.0 --port=8080 --allow-root --no-browser
